#!/bin/bash
# Compile and setup ready to run in a separate directory
# usage:  ./setup <directory name>

mkdir $1 2> /dev/null

#Compile
make

#Setup dir
if [ $? == 0 ]; then
  mv 3d_gpe $1
  cp 3d_gpe.f90 run.sh $1
fi
